### ISSUE TITLE
Compile Error: AssetJSON

### ISSUE THREAD

**Issue by darmie** [underscorediscovery/snow#103]
I tried compiling my snow app, and I get this error:

```
Error: ./src/snow/systems/assets/AssetJSON.cpp: In member function 'void snow::systems::assets::AssetJSON_obj::__construct(snow::systems::assets::Assets, String, Dynamic)':
./src/snow/systems/assets/AssetJSON.cpp:42:21: error: 'class snow::systems::assets::AssetJSON_obj' has no member named 'set_json'
 HXLINE( 417)  this->set_json(_json);
```

**Comment by darmie** [comment]
Fixed it by removing `-dce full` from build flags

**Comment by ruby0x1** [comment]
wonder if it should be reported as a bug to haxe, it seems unintended that a used function gets lost by dce? I know it can be annotated with @:keep but for that to happen on every used function is not the purpose

**Comment by darmie** [comment]
I was wondering if it's because it's a get/set function...

It's best to report it to Haxe, because it won't make sense to have to `@:keep` all functions.
