### ISSUE TITLE
Web; fullscreen should update window sizes and emit size events

### ISSUE THREAD

**Issue by smvilar** [underscorediscovery/snow#54]
When setting the `config.window.fullscreen` flag, `Luxe.screen.size` will be still set as the `config.window.width` and `config.window.height`

Example:
```
	override function config(config:AppConfig):AppConfig {
		config.window.width = 640;
		config.window.height = 480;
		config.window.fullscreen = true;

		return config;
	}

	override function ready() {
		trace(Luxe.screen.size); // 640, 480
	}
```

**Comment by smvilar** [comment]
Hi @underscorediscovery, any news on this issue?

I noticed the only way to get the right values is through `Luxe.core.app.window.handle.width` and `Luxe.core.app.window.handle.height`. Not even `Luxe.core.app.window.width` and `height` is updated.

**Comment by underscorediscovery** [comment]
Did you try it in latest? It should be accounted for (like [here](https://github.com/underscorediscovery/luxe/issues/186))

**Comment by smvilar** [comment]
Hi, sorry for the delayed answer. I think the latest commits (e.g. 98f37eeca53d92f223efafd0fa5d581e1b8e9be3) fixed it.

**Comment by underscorediscovery** [comment]
:+1:
