### ISSUE TITLE
flow run error

### ISSUE THREAD

**Issue by DQvsRA** [underscorediscovery/snow#58]
I install flow and snow as mentioned in guide, copy base template and try to run in throw flow run, but i have this error
![image](https://cloud.githubusercontent.com/assets/442111/5433043/a1228c52-845c-11e4-95bb-9a6a72908ea9.png)

**Comment by underscorediscovery** [comment]
if this comes up again, feel free to reopen. But I'll close this for now due to lack of feedback. :)
