### ISSUE TITLE
Audio; Web implementation dynamic volume

### ISSUE THREAD

**Issue by mbalestrini** [underscorediscovery/snow#63]
Web Audio:
Changing the volume of an already looping sound doesn't work.
I saw that snow.platform.web.audio.howlerjs.Sound.set_volume set a volume_dirty flag (that's seems to be used only on play() and loop() methods), and that's it.
I think the same thing happens with pan

**Comment by underscorediscovery** [comment]
Hi! 
Yes when I was implementing howler it seemed to resist changing the volume as one would expect to do, and it required some forcing to get it to update. This led to the dirty flag so it can force it elsewhere, but this was something that needs to be addressed.

A focus sheet on audio will ensure all platforms are cohesive during the alpha, so it will be resolved quite soon :) Thanks for the report!

**Comment by underscorediscovery** [comment]
Someone on the chat mentioned that you can get around this by using the `sound.info.handle` (which is the Howl instance) directly on web target, but this will be resolved relatively soon anyway.

**Comment by underscorediscovery** [comment]
This should be fixed in the latest commits. There were also some bugs in chrome and howler that were fixed. All properties should have parity again with native.
