### ISSUE TITLE
native and web; GLUniformLocation inconsistent behavior 

### ISSUE THREAD

**Issue by haxiomic** [underscorediscovery/snow#67]
On web, null is returned if getUniformLocation fails, whereas on native, -1 is returned, consequently there's no platform independent way to check if a GLUniformLocation is valid.

I've been using this abstract in [native/render/opengl/GL.hx](https://github.com/underscorediscovery/snow/blob/newtypedarrays/snow/platform/native/render/opengl/GL.hx#L51) (newtypedarray branch) that treats GLUniformLocation as a Null<Int> checks if its value is -1 when comparing with null

```haxe
abstract GLUniformLocation(Null<Int>) from Int{
    @:op(A == B) inline public function equality(rhs:Null<Int>) return rhs == null ? this < 0 : this == rhs; //allow for comparison with null
    @:op(A != B) inline public function invEquality(rhs:Null<Int>) return !equality(rhs);
    @:to inline public function toInt():Int return this == null ? -1 : this;
}
```
I suspect it's not bullet proof but do you think this is the right approach?

**Comment by underscorediscovery** [comment]
The right place to check for the correct behaviour is the [WebGL spec](https://www.khronos.org/registry/webgl/specs/latest/1.0/)

> The return value is null if name does not correspond to an active uniform variable in the passed program.
> Returns null if name starts with one of the reserved WebGL prefixes per GLSL Constructs.
> Returns null if any OpenGL errors are generated during the execution of this function.

**Comment by underscorediscovery** [comment]
But keep this issue open, I'll take a look at matching the spec on native in the best way for the future changes (native stuff)
