### ISSUE TITLE
building native libs doesn't function for ios

### ISSUE THREAD

**Issue by jonbro** [underscorediscovery/snow#69]
http://underscorediscovery.github.io/snow/guide/native-layer.html
following the directions here, only the arm7 lib is built. Additionally, when building a luxe project for iOS, it fails to copy the correct lib files (due to them missing possibly?) so the build breaks with

```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /usr/lib/haxe/lib/snow/git/ndll/iPhone/libsnow.iphoneos-64.a (No such file or directory)
```

**Comment by underscorediscovery** [comment]
So, the build server had a typo which I fixed, 
You should be able to get the ndll folder correctly from here now:
http://build.luxeengine.com/snow 
As written [up here](http://snowkit.org/2015/03/23/snowkit-dev-log-2-history/), the order of arguments typo was causing some confusion to the script and it was mixing up the folders.


For building _snow_ manually for iOS, you'd want to use something along the lines of:

`flow build ios --archs armv6,armv7,armv7s,arm64,sim,sim64 --d static_link`

When you build your app - Xcode takes care of the build details, so you don't have to do any of that.

For the application side, It would be :

- make sure you have snow/ndll/iPhone in place with the build server output (or your own)
- `flow run ios` generates the Xcode project,  just hit play in xcode it handles the rest (including the archs etc, which you would configure normally via Xcode itself).

I'll make a note about the iOS rebuilds for snow docs, sorry for the confusion!
