### ISSUE TITLE
Window; web; Window does not receive resize events if config.fullscreen is true.

### ISSUE THREAD

**Issue by Herschel** [underscorediscovery/snow#72]
When fullscreen mode is activated by setting `config.window.fullscreen`, the window is never added to the `windowing.fs_windows` array and will never receive resize events. The user must explicitly call `app.window.fullscreen = true;` to add the window to the `fs_windows` array and receive size events.

**Comment by underscorediscovery** [comment]
let me know if you have an problems with the fix!

**Comment by underscorediscovery** [comment]
err, over enthused, let me try that again

**Comment by underscorediscovery** [comment]
_now_ it shouldn't break everything !

**Comment by Herschel** [comment]
Thanks!
