### ISSUE TITLE
broken link?

### ISSUE THREAD

**Issue by raould** [underscorediscovery/snow#81]
https://underscorediscovery.github.io/flow/usage/index.html
from
https://underscorediscovery.github.io/flow/flow.html#guide
returns
404
for me
(might be good to in general run a link checker / html static checker.)

**Comment by raould** [comment]
p.s. sorry, duh, shoulda made the entry on the flow tracker?

**Comment by underscorediscovery** [comment]
This should be fixed.

Just to note, 
The documentation (and the documentation generator) is an ongoing part of development. 
I appreciate the report, but you do not have to file an issue for every minor doc bug at this time.
