### ISSUE TITLE
iOS: running slow on a real device

### ISSUE THREAD

**Issue by tanis2000** [underscorediscovery/snow#86]
Hi, I've just started evaluating snow+flow+luxe and I run a quick test on iOS as this is my reference platform for a new project. 

I came up with a simple benchmark (quickly ported from the Lime BunnyMark):
https://github.com/tanis2000/luxe-test-bunnymark

Running it on an actual device (iPhone 6) shows very low FPS (5/6) even with only 500 sprites on the screen.

Is this a problem with the native stuff, the renderer or what else could be the cause?

Thanks for the help!

**Comment by underscorediscovery** [comment]
Bunnymark and similar tests are a waste of time as a benchmark,
But if you've read the dev logs you will know why you're seeing this.
There are many ways to draw many things even still, but this brute force approach is not one of them.

Lastly, make sure you set your project scheme off of debug (the default) or else you won't see useful results anyway.

**Comment by tanis2000** [comment]
@underscorediscovery I haven't gone through the whole dev logs, but I tried to run the luxemark as well and the performance is exactly the same. 

The Sprite is always the same and uses the same asset. I'll skim through the dev logs to understand more about this, but what I expected was to have all of them being batched together in a single drawcall considering that they're all the same texture. I'm sure I'm not understanding something of what happens underneath. :)

I'm on gitter if you've got some time to talk about this issue.

**Comment by underscorediscovery** [comment]
I'm expanded on this in the dev logs (5 and 7 at least, and there are numerous threads on snowkit regarding the same questions with the same answers)

**Comment by tanis2000** [comment]
I understand the frustration of having to explain the same thing over and over. Don't take it personal. I read the dev logs and now what you're talking about is clear. I just didn't even know about those posts before you told me. 
Cheers!

**Comment by underscorediscovery** [comment]
No problem, don't take my short responses as offense of any kind, just occupied :) Thanks for the questions

**Comment by tanis2000** [comment]
Before closing this issue I just wanted to say that Snowkit is awesome :)
I'm looking forward to the new renderer! ;)
