### ISSUE TITLE
windowing; web; fullscreen broken by alpha 2 changes

### ISSUE THREAD

**Issue by nslottow** [underscorediscovery/snow#89]
While it looks like the canvas element gets sized correctly, it seems like the viewport/snow windowing system isn't getting the right events upon startup.  In Chrome, this results in a small viewport at the bottom left of the screen.  In Safari, fullscreen appears to work non-deterministically- maybe it's an event ordering problem.  FYI we're testing with luxe.Camera.SizeMode.fit.

@kneeko and I are looking into this but were wondering if anything springs to mind for you @underscorediscovery.

**Comment by kneeko** [comment]
A little clarification, this is only broken on a high-dpi screen (when device pixel ratio is not 1.0).

**Comment by nslottow** [comment]
Ah, so with that info, and knowing that the canvas stuff (the actual snow windowing part) looks like it's working, this issue should probably go on the luxe repo.

**Comment by nslottow** [comment]
After looking into this a little bit more, it turns out that there is a race between the first time that `snow.core.web.Runtime.update_window_bounds()` gets called and `Luxe.screen` gets initialized based on the size of the canvas element.

Because `update_window_bounds()` is only called in `snow.core.web.Runtime.loop()`, the canvas element isn't scaled by the device-pixel-ratio until the first frame after `Snow.ready` is set to `true`.

It gets a tiny bit more complicated: `luxe.Core.ready()` asynchronously loads the default font before calling `luxe.Core.init()`.
So there's a chance that the first ready frame happens before calling `luxe.Core.init()`, but it's also likely not to happen.

So that explains why `Luxe.screen` is non-deterministically set incorrectly in Safari. I've only tested in Safari and Chrome, and this only repros in Safari, but there's reason to believe it could be a problem in other browsers too.

I'm preparing a PR to fix this and another scaling bug on iOS 9 Safari (see https://github.com/bigwheel-framework/bigwheel/issues/25 for a similar issue). Thanks a lot @kneeko for working on this with me.

**Comment by underscorediscovery** [comment]
ah yea, I was busy fussing with some things last minute on the web side that I changed to use this new updated function and must have missed that it syncs up on update - and then I fixed a bug where the timing was starting the loop before the ready event - so I just missed that. I think I can fix it pretty quick but you're welcome to, if you have done the effort, PR and we'll go from there!

**Comment by nslottow** [comment]
Alright :) The fix we came up with was just to call `update_window_bounds()` at the end of `create_window()`.  So I'll do a PR for that and see if it looks right to you.  I'll just do the iOS scaling thing separately since I'm not quite sure how to condition it just for iOS 9 yet.

**Comment by underscorediscovery** [comment]
That sounds good, I don't want to get too nuanced with obscure mobile specific web junk till the rest is a bit more battle tested. Just calling the update bounds function once up front sounds just fine as a fix for now :point_up_2:
