### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by unodgs** [underscorediscovery/snow#91]
I have installed all linc libs, haxe 3.3.0 (but I also tried 3.2.X), flow alpha-2. But when I run `haxelib run flow build` in snow directory I get this message:
```
~/dev/haxe/snow/git /master> haxelib run flow build
flow / 1.0.0-alpha.2 (node.js v0.12.7)
flow / target is mac ( arch 64 )
flow / build only
flow / haxe version 3.3.0 (git build development @ 4688e8f)

flow / build - snow 1.0.0-alpha.2 for mac
flow / build - running haxe ...
/usr/local/lib/haxe/std/haxe/macro/Context.hx:258: characters 9-46 : Type not found 'Main.UserConfig'
snow/types/TypeCreate.hx:45: characters 50-72 : Called from
snow/types/Types.hx:71: characters 12-36 : Called from
Aborted
```
Probably this is sth trivial but I can't find what it is..

**Comment by underscorediscovery** [comment]
You wouldn't try to build snow, you would build something that uses snow (snow is a library). Try `samples/basic` and run `haxelib run flow build` from that folder instead :)

**Comment by unodgs** [comment]
I got back to my old project where I used very old version of snow and I had to build snow first. That's why I tried the same with the new newer version :) I followed your advice but unfortunately I get:
```
~/dev/haxe/snow/git/samples/basic /master> haxelib run flow build
flow / 1.0.0-alpha.2 (node.js v0.12.7)
flow / target is mac ( arch 64 )
flow / build only
flow / haxe version 3.3.0 (git build development @ 4688e8f)

flow / build - snow.basic 1.0.0 for mac
flow / build - running haxe ...
File "src/typing/typeload.ml", line 102, characters 27-33: Assertion failed
```
same error for any project from samples.

**Comment by underscorediscovery** [comment]
That's an internal error from the haxe compiler, nothing I can do about that unfortunately!

**Comment by unodgs** [comment]
You were right. With 3.2.1 everything works as expected. Thank you for your help!

**Comment by underscorediscovery** [comment]
No problem. For reference, we test and make sure everything is working on compiler versions during their RC releases, before that time they aren't officially supported (even if I do frequently test or fix things against the new versions, it is not considered a priority).

**Comment by kevinresol** [comment]
Is there any particular issue on the haxe repo that we can keep track on?

**Comment by underscorediscovery** [comment]
Keep track on what in particular @kevinresol?

**Comment by kevinresol** [comment]
Oh, please ignore me. Because I thought this was a bug of the compiler so there should be a issue tracking the bug. But then I realized that it is not a bug but a breaking change about genericBuild. So, no more worries. Thanks.

**Comment by underscorediscovery** [comment]
Ah I see. Not sure this was specifically genericBuild related, but there are some changes to that that are still not well defined, so we will wait to see what the compiler decides to do and we will adapt when the RC is ready.

**Comment by NtrfAtZNS** [comment]
There was kinda strange resolution in (https://github.com/HaxeFoundation/haxe/issues/4825#issuecomment-207061028). They decided to implement `@:eager` meta but didn't reopen the issue.
